### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by admapop** [flexdinesh/react-socks#31] opened 2019-09-23 07:17 UTC
The react website I'm building at the moment is throwing this error in the console.

It works just fine on localhost, but as soon as I deploy it to Netlify, the page is blank and I get this error in console pointed at react-socks/dist/index.js

I have no idea what could be causing this and why it gets triggered only in production.

**Comment by dbryantm** [comment] 2019-09-23 17:50
I noticed this also since the release of 2.1.0 so I've reverted back to 2.0.2 for the time being though I've discovered it definitely affects apps using CRA and during the build script.

React & React DOM: 16.9.0
CRA: 3.1.1

**Comment by wileybaba** [comment] 2019-10-03 15:00
I am also getting this error with v2.1.0 with a CRA build.  I'm going to revert to 2.0.2 and see if I have any luck.

**Comment by flexdinesh** [comment] 2019-10-24 00:32
@admapop @dbryantm @wileybaba I added the project to a new create-react-app and tried to build it and couldn't see any error. Is this error Netlify specific or does it happen when you build the project in local?

This is what I tried —

1. new create-react-app
2. add `react-socks` and an Example component that uses it
3. Run `yarn build`
4. Serve locally with [http-server](https://www.npmjs.com/package/http-server) with the command `http-server build -c-1`

**Comment by dbryantm** [comment] 2019-10-25 13:28
@flexdinesh, looks like some release of CRA/React seems to fix the issue. Not sure of the exact version that would correct what we were experiencing from before though. I'm currently on the following:
```
react: 16.11.0
react-dom: 16.11.0
react-scripts: 3.2.0
```
When I was still experiencing the mentioned issue I was on the following: 
```
react: 16.9.0
react-dom: 16.9.0
react-scripts: 3.1.1
``` 
You might want to attempt installing those specific versions and see if you're able to reproduce? The short term answer would definitely be to encourage people to upgrade if possible. Could you try this @admapop and @wileybaba? Thanks in advance!

**Comment by wileybaba** [comment] 2019-10-28 18:08
I update react and react-dom to 16.11.0 and my build is now working with react-socks 2.1 as of now.  My suspicion is that the error was coming from something within the build process in CRA

**Comment by flexdinesh** [comment] 2019-10-28 20:12
Thanks for the confirmation @dbryantm @wileybaba. Glad things are working fine for you now. I'm gonna close this issue.

**Closed** 2019-10-28 20:12 UTC

**Comment by tonytoth** [comment] 2019-11-12 10:48
I had the same issue and it worked for me with these versions:
`"[react](https://npmjs.com/package/react)": "^16.11.0",`
`"[react-dom](https://npmjs.com/package/react-dom)": "^16.11.0",`
`"[react-socks](https://npmjs.com/package/react-socks)": "2.0.2",`
Thank you very much guys !

**Comment by rusyurchenko** [comment] 2019-12-02 20:23
Same issue with 
```
react: 16.12.0
react-dom: 16.12.0
react-socks: 2.1.0
```
